name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}
          build_configuration: staging
          base_href: /ghrv-frontend/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/
